"""Didactic library: hand-authored cases with provenance. Not a generalization benchmark."""

from __future__ import annotations

ZERO = ["0"] * 7
M = ["1", "0", "0", "0", "0", "0", "0"]
L = ["0", "1", "0", "0", "0", "0", "0"]
T = ["0", "0", "1", "0", "0", "0", "0"]
V = ["0", "1", "-1", "0", "0", "0", "0"]
E = ["1", "2", "-2", "0", "0", "0", "0"]
P = ["1", "1", "-1", "0", "0", "0", "0"]

SOURCE = {
    "kind": "synthetic",
    "author": "NatalIA maintainers",
    "license": "Same as this repository",
    "note": "Original didactic formalizations, not copied from copyrighted problem sets.",
}


def _rel(claim_id, lhs, op, rhs):
    return {"kind": "relation", "id": claim_id, "lhs": lhs, "op": op, "rhs": rhs}


def _sub(title, latex, variables, assumptions, claims, budget=5000):
    return {
        "schema_version": "1.0",
        "title": title,
        "source_latex": latex,
        "variables": variables,
        "assumptions": assumptions,
        "claims": claims,
        "budget_ms": budget,
    }


def _case(
    *,
    ident,
    theme,
    title,
    question,
    context,
    recommended_reason,
    expected_verdict,
    expected_evidence,
    expected_justification,
    limitations,
    variants,
    submission,
    featured=False,
):
    return {
        "id": ident,
        "theme": theme,
        "title": title,
        "question": question,
        "context": context,
        "recommended_reason": recommended_reason,
        "expected_verdict": expected_verdict,
        "expected_evidence": expected_evidence,
        "expected_justification": expected_justification,
        "source": SOURCE,
        "limitations": limitations,
        "pedagogical_variants": variants,
        "featured": featured,
        "submission": submission,
    }


CASES = [
    _case(
        ident="lib-01-kinetic",
        theme="physics_in_fragment",
        title="Energia cinética não negativa",
        question="Se a massa é positiva, a energia cinética clássica pode ser negativa?",
        context="Afirmação elementar de mecânica newtoniana no fragmento polinomial.",
        recommended_reason="Primeiro exemplo SMT com dimensões físicas reais.",
        expected_verdict="ACCEPTED",
        expected_evidence="smt_relative",
        expected_justification="Com m>0, m v^2 / 2 é um quadrado escalado e não é negativo.",
        limitations="Não prova relatividade nem define o que é energia fora da fórmula declarada.",
        variants=["Remova m>0 e observe a refutação.", "Some energia ao momento e veja INVALID."],
        submission=_sub(
            "Energia cinética não negativa",
            r"E_k = \frac{1}{2} m v^2 \geq 0,\quad m>0",
            {"m": {"dimension": M}, "v": {"dimension": V}},
            [{"lhs": "m", "op": ">", "rhs": "0"}],
            [_rel("kinetic-energy", "m*v**2/2", ">=", "0")],
        ),
        featured=True,
    ),
    _case(
        ident="lib-02-square-vs-linear",
        theme="counterexamples",
        title="O quadrado não domina a identidade",
        question="x² ≥ x vale para todo real?",
        context="Desigualdade falsa usada para exercitar contraexemplo racional.",
        recommended_reason="Mostra evidência inspecionável, não só um selo de refutação.",
        expected_verdict="REFUTED",
        expected_evidence="exact_rational_witness",
        expected_justification="Qualquer x em (0,1) viola a desigualdade; o checker racional confirma.",
        limitations="A testemunha é um ponto; o gráfico, se houver, é ilustração.",
        variants=["Restrinja x≥1 para obter aceite no fragmento SMT."],
        submission=_sub(
            "x**2 >= x para reais",
            r"x^2 \geq x \quad \forall x \in \mathbb{R}",
            {"x": {"dimension": ZERO}},
            [],
            [_rel("square-ge-id", "x**2", ">=", "x")],
        ),
        featured=True,
    ),
    _case(
        ident="lib-03-energy-plus-momentum",
        theme="dimensional_consistency",
        title="Energia somada ao momento",
        question="Podemos somar energia e momento linear na mesma expressão?",
        context="Erro dimensional clássico antes de qualquer solver.",
        recommended_reason="Mostra que o laboratório recusa a formalização, não ‘tenta provar mesmo assim’.",
        expected_verdict="INVALID",
        expected_evidence="static_compile",
        expected_justification="Expoentes SI de energia e momento diferem; a soma é ilegítima.",
        limitations="Não converte unidades; um preset dimensional não é uma conversão de escala.",
        variants=["Compare cada grandeza com zero separadamente."],
        submission=_sub(
            "Energia somada ao momento",
            r"\tfrac12 m v^2 + m v \geq 0",
            {"m": {"dimension": M}, "v": {"dimension": V}},
            [{"lhs": "m", "op": ">", "rhs": "0"}],
            [_rel("mixed", "m*v**2/2 + m*v", ">=", "0")],
        ),
        featured=True,
    ),
    _case(
        ident="lib-04-rational-limit",
        theme="supported_and_unsupported_limits",
        title="Limite racional em infinito",
        question="O limite de (2x²+1)/(x²+3) em +∞ é 2?",
        context="CAS consultivo: mesmo coincidindo, não certifica.",
        recommended_reason="Separa resultado indicativo de prova.",
        expected_verdict="ABSTAIN",
        expected_evidence="cas_advisory",
        expected_justification="SymPy pode coincidir com 2, mas o status permanece unknown.",
        limitations="Não é indecidibilidade matemática; é limite do adapter local.",
        variants=["Use uma identidade polinomial se quiser certificado SMT."],
        submission=_sub(
            "Limite racional em infinito",
            r"\lim_{x\to\infty}(2x^2+1)/(x^2+3)=2",
            {"x": {"dimension": ZERO}},
            [],
            [
                {
                    "kind": "limit",
                    "id": "ratio",
                    "expression": "(2*x**2+1)/(x**2+3)",
                    "variable": "x",
                    "target": "infinity",
                    "expected": "2",
                }
            ],
        ),
    ),
    _case(
        ident="lib-05-proof-hole",
        theme="proof_gaps",
        title="Dedução incompleta",
        question="Uma lacuna declarada pode gerar aceite?",
        context="O usuário admite que falta um passo.",
        recommended_reason="Ensina que buraco explícito bloqueia o veredito.",
        expected_verdict="ABSTAIN",
        expected_evidence="unavailable",
        expected_justification="proof_hole permanece unknown por contrato.",
        limitations="O sistema não inventa todas as lacunas de um texto informal.",
        variants=["Combine com uma afirmação falsa: a refutação prevalece."],
        submission=_sub(
            "Dedução incompleta",
            "Passo geométrico omitido.",
            {"x": {"dimension": ZERO}},
            [],
            [{"kind": "proof_hole", "id": "missing-lemma", "description": "Falta justificar o passo."}],
        ),
    ),
    _case(
        ident="lib-06-contradiction",
        theme="contradictory_premises",
        title="Premissas contraditórias",
        question="Premissas impossíveis autorizam qualquer conclusão?",
        context="Bloqueio de aceite vacuoso.",
        recommended_reason="Contrato científico: inconsistência não vira prova.",
        expected_verdict="ABSTAIN",
        expected_evidence="smt_relative",
        expected_justification="x>1 e x<0 é UNSAT; nenhuma afirmação é aceita.",
        limitations="Não classifica a teoria como explosiva além deste encoding.",
        variants=["Troque uma premissa para recuperar consistência."],
        submission=_sub(
            "Premissas contraditórias",
            r"x>1 \land x<0 \implies x^2 \geq 0",
            {"x": {"dimension": ZERO}},
            [{"lhs": "x", "op": ">", "rhs": "1"}, {"lhs": "x", "op": "<", "rhs": "0"}],
            [_rel("anyway", "x**2", ">=", "0")],
        ),
    ),
    _case(
        ident="lib-07-singularity",
        theme="domains_and_singularities",
        title="x/x = 1 sem domínio",
        question="Cancelar x/x é válido em todos os reais?",
        context="Singularidade em zero.",
        recommended_reason="Domínio omitido gera abstenção, não simplificação silenciosa.",
        expected_verdict="ABSTAIN",
        expected_evidence="smt_relative",
        expected_justification="Sem x≠0 o adapter não estabelece segurança de domínio.",
        limitations="Não prova análise em distribuições.",
        variants=["lib-08 adiciona x≠0."],
        submission=_sub(
            "x/x == 1 sem domínio",
            r"x/x = 1",
            {"x": {"dimension": ZERO}},
            [],
            [_rel("cancel", "x/x", "==", "1")],
        ),
    ),
    _case(
        ident="lib-08-domain-fixed",
        theme="domains_and_singularities",
        title="x/x = 1 com x ≠ 0",
        question="Com o zero excluído, a identidade racional fecha?",
        context="Mesma fórmula, domínio explícito.",
        recommended_reason="Mostra que o aceite depende das premissas, não de um truque de UI.",
        expected_verdict="ACCEPTED",
        expected_evidence="smt_relative",
        expected_justification="Com x≠0, x/x−1 é identicamente nulo no domínio.",
        limitations="Ainda é aritmética real SMT, não um kernel Lean.",
        variants=["Volte à variante sem domínio."],
        submission=_sub(
            "x/x == 1 com x != 0",
            r"x\neq 0 \implies x/x = 1",
            {"x": {"dimension": ZERO}},
            [{"lhs": "x", "op": "!=", "rhs": "0"}],
            [_rel("cancel", "x/x", "==", "1")],
        ),
    ),
    _case(
        ident="lib-09-oscillation",
        theme="supported_and_unsupported_limits",
        title="Limite oscilatório",
        question="sin(x)/x em +∞ está no adapter local?",
        context="Fora do fragmento assintótico implementado.",
        recommended_reason="Deixa visível um não-suporte honesto.",
        expected_verdict="ABSTAIN",
        expected_evidence="cas_advisory",
        expected_justification="sin não é suportado; o resultado não é ‘indecidível em geral’.",
        limitations="Há teoria clássica para esse limite; o laboratório local não a implementa.",
        variants=["Troque por uma razão polinomial."],
        submission=_sub(
            "Limite oscilatório",
            r"\lim_{x\to\infty}\sin(x)/x",
            {"x": {"dimension": ZERO}},
            [],
            [
                {
                    "kind": "limit",
                    "id": "osc",
                    "expression": "sin(x)/x",
                    "variable": "x",
                    "target": "infinity",
                    "expected": "0",
                }
            ],
        ),
    ),
    _case(
        ident="lib-10-square-nonneg",
        theme="identities_and_inequalities",
        title="Quadrado não negativo",
        question="x² ≥ 0 vale em todos os reais?",
        context="Identidade SMT mínima.",
        recommended_reason="Caso positivo curto para o modo guiado.",
        expected_verdict="ACCEPTED",
        expected_evidence="smt_relative",
        expected_justification="Negação exige x²<0, UNSAT em QF_NRA.",
        limitations="Não cobre formas semidefinidas em várias variáveis com encoding diferente.",
        variants=["Troque para x² ≥ 1 e obtenha refutação."],
        submission=_sub(
            "Quadrado não negativo",
            r"x^2 \geq 0",
            {"x": {"dimension": ZERO}},
            [],
            [_rel("square", "x**2", ">=", "0")],
        ),
    ),
    _case(
        ident="lib-11-binomial",
        theme="identities_and_inequalities",
        title="Identidade binomial",
        question="(x+1)² = x² + 2x + 1?",
        context="Expansão polinomial.",
        recommended_reason="Aceite por identidade, sem dimensões físicas.",
        expected_verdict="ACCEPTED",
        expected_evidence="smt_relative",
        expected_justification="Polinômio diferença é identicamente nulo.",
        limitations="Não prova o binômio geral de Newton.",
        variants=["Mude o 2 para 3 e observe a refutação."],
        submission=_sub(
            "Identidade binomial",
            r"(x+1)^2 = x^2+2x+1",
            {"x": {"dimension": ZERO}},
            [],
            [_rel("expand", "(x+1)**2", "==", "x**2 + 2*x + 1")],
        ),
    ),
    _case(
        ident="lib-12-restricted-true",
        theme="identities_and_inequalities",
        title="x² ≥ x sob x ≥ 1",
        question="A desigualdade falsa vira verdadeira num domínio menor?",
        context="Refinamento pedagógico da lib-02.",
        recommended_reason="Compare versões: o objeto formal mudou.",
        expected_verdict="ACCEPTED",
        expected_evidence="smt_relative",
        expected_justification="Em [1,∞) a parábola está acima da identidade.",
        limitations="Uma premissa extra não é ‘correção automática’ da afirmação original.",
        variants=["Use x≥0: ainda é falso."],
        submission=_sub(
            "x**2 >= x para x >= 1",
            r"x\geq 1 \implies x^2 \geq x",
            {"x": {"dimension": ZERO}},
            [{"lhs": "x", "op": ">=", "rhs": "1"}],
            [_rel("square-ge-id", "x**2", ">=", "x")],
        ),
    ),
    _case(
        ident="lib-13-restricted-false",
        theme="counterexamples",
        title="x² ≥ x sob x ≥ 0",
        question="Não negatividade basta para x² ≥ x?",
        context="Domínio ainda contém (0,1).",
        recommended_reason="Mostra que restringir mal o domínio não salva a afirmação.",
        expected_verdict="REFUTED",
        expected_evidence="exact_rational_witness",
        expected_justification="x=1/2 ≥ 0 e (1/2)² < 1/2.",
        limitations="A testemunha depende das premissas declaradas.",
        variants=["Suba o corte para x≥1."],
        submission=_sub(
            "x**2 >= x para x >= 0",
            r"x\geq 0 \implies x^2 \geq x",
            {"x": {"dimension": ZERO}},
            [{"lhs": "x", "op": ">=", "rhs": "0"}],
            [_rel("square-ge-id", "x**2", ">=", "x")],
        ),
    ),
    _case(
        ident="lib-14-mass-plus-time",
        theme="dimensional_consistency",
        title="Massa somada ao tempo",
        question="m + t tem dimensão?",
        context="Inconsistência SI óbvia.",
        recommended_reason="Segundo erro dimensional, agora sem energia.",
        expected_verdict="INVALID",
        expected_evidence="static_compile",
        expected_justification="Massa e tempo não são somáveis.",
        limitations="Não interpreta unidades naturais.",
        variants=["Use m*t se a quantidade pretendida for outro objeto."],
        submission=_sub(
            "Massa somada ao tempo",
            r"m+t \geq 0",
            {"m": {"dimension": M}, "t": {"dimension": T}},
            [],
            [_rel("mix", "m+t", ">=", "0")],
        ),
    ),
    _case(
        ident="lib-15-length-plus-velocity",
        theme="dimensional_consistency",
        title="Comprimento somado à velocidade",
        question="ℓ + v é uma grandeza física?",
        context="Outro par SI incompatível.",
        recommended_reason="Diversifica o catálogo além de energia/momento.",
        expected_verdict="INVALID",
        expected_evidence="static_compile",
        expected_justification="[L] ≠ [L T⁻¹].",
        limitations="Preset de velocidade não converte km/h em m/s.",
        variants=["Compare ℓ com 0 e v com 0 em afirmações distintas."],
        submission=_sub(
            "Comprimento somado à velocidade",
            r"\ell + v \geq 0",
            {"ell": {"dimension": L}, "v": {"dimension": V}},
            [],
            [_rel("mix", "ell + v", ">=", "0")],
        ),
    ),
    _case(
        ident="lib-16-x-positive-false",
        theme="counterexamples",
        title="Todo real é positivo?",
        question="x > 0 vale irrestrito?",
        context="Refutação imediata.",
        recommended_reason="Contraexemplo trivial para ler a substituição.",
        expected_verdict="REFUTED",
        expected_evidence="exact_rational_witness",
        expected_justification="x=0 ou x negativo violam x>0.",
        limitations="Não discute ordenação em outros corpos.",
        variants=["Adicione x>1 como premissa."],
        submission=_sub(
            "Todo real é positivo",
            r"x>0",
            {"x": {"dimension": ZERO}},
            [],
            [_rel("pos", "x", ">", "0")],
        ),
    ),
    _case(
        ident="lib-17-square-lt-zero",
        theme="contradictory_premises",
        title="Quadrado estritamente negativo",
        question="Existe real com x² < 0?",
        context="Premissa impossível usada como hipótese.",
        recommended_reason="Outra forma de vacuidade, sem duas desigualdades lineares.",
        expected_verdict="ABSTAIN",
        expected_evidence="smt_relative",
        expected_justification="x²<0 é UNSAT; aceite vacuoso bloqueado.",
        limitations="Corpos reais fechados não estão no encoding.",
        variants=["Use x² ≤ -1."],
        submission=_sub(
            "Premissa x**2 < 0",
            r"x^2<0 \implies x=0",
            {"x": {"dimension": ZERO}},
            [{"lhs": "x**2", "op": "<", "rhs": "0"}],
            [_rel("then-zero", "x", "==", "0")],
        ),
    ),
    _case(
        ident="lib-18-reciprocal-product",
        theme="domains_and_singularities",
        title="x · (1/x) = 1 com domínio",
        question="O inverso cancela após excluir zero?",
        context="Forma alternativa de lib-08.",
        recommended_reason="Mesma ideia, outra AST, para não duplicar só o nome da variável.",
        expected_verdict="ACCEPTED",
        expected_evidence="smt_relative",
        expected_justification="Com x≠0, o produto é 1.",
        limitations="Não trata 0⁺ em limites.",
        variants=["Remova x≠0."],
        submission=_sub(
            "Produto pelo inverso",
            r"x\neq 0 \implies x\cdot(1/x)=1",
            {"x": {"dimension": ZERO}},
            [{"lhs": "x", "op": "!=", "rhs": "0"}],
            [_rel("inv", "x*(1/x)", "==", "1")],
        ),
    ),
    _case(
        ident="lib-19-reciprocal-open",
        theme="domains_and_singularities",
        title="x · (1/x) = 1 sem domínio",
        question="E sem excluir zero?",
        context="Par pedagógico de lib-18.",
        recommended_reason="Limite suportado vs não suportado no mesmo tema.",
        expected_verdict="ABSTAIN",
        expected_evidence="smt_relative",
        expected_justification="Divisão potencialmente indefinida.",
        limitations="Abstenção operacional/de fragmento, não teorema de indecidibilidade.",
        variants=["lib-18."],
        submission=_sub(
            "Produto pelo inverso sem domínio",
            r"x\cdot(1/x)=1",
            {"x": {"dimension": ZERO}},
            [],
            [_rel("inv", "x*(1/x)", "==", "1")],
        ),
    ),
    _case(
        ident="lib-20-kinetic-unrestricted",
        theme="physics_in_fragment",
        title="Energia cinética sem massa positiva",
        question="Sem m>0 a energia clássica permanece não negativa?",
        context="Massa pode ser negativa no encoding real.",
        recommended_reason="Caso físico negativo dentro da capacidade do adapter.",
        expected_verdict="REFUTED",
        expected_evidence="exact_rational_witness",
        expected_justification="m negativo e v≠0 tornam m v²/2 negativo.",
        limitations="Não afirma que massa negativa existe na natureza.",
        variants=["Reponha m>0."],
        submission=_sub(
            "Energia cinética sem m>0",
            r"\tfrac12 m v^2 \geq 0",
            {"m": {"dimension": M}, "v": {"dimension": V}},
            [],
            [_rel("kinetic-energy", "m*v**2/2", ">=", "0")],
        ),
    ),
    _case(
        ident="lib-21-momentum-nonneg",
        theme="physics_in_fragment",
        title="Momento sempre positivo?",
        question="m v ≥ 0 se m>0?",
        context="Velocidade pode ser negativa.",
        recommended_reason="Afirmação física falsa no fragmento.",
        expected_verdict="REFUTED",
        expected_evidence="exact_rational_witness",
        expected_justification="v negativo refuta com m positivo.",
        limitations="Não modela vetores em 3D.",
        variants=["Use m v² ≥ 0."],
        submission=_sub(
            "Momento sempre não negativo",
            r"m>0 \implies m v \geq 0",
            {"m": {"dimension": M}, "v": {"dimension": V}},
            [{"lhs": "m", "op": ">", "rhs": "0"}],
            [_rel("momentum", "m*v", ">=", "0")],
        ),
    ),
    _case(
        ident="lib-22-force-balance",
        theme="physics_in_fragment",
        title="Força declarada como energia",
        question="Se F é marcado como energia, F = m a passa na compilação?",
        context="Erro de dimensão na segunda lei.",
        recommended_reason="Caso físico inválido: a etiqueta dimensional contradiz a equação.",
        expected_verdict="INVALID",
        expected_evidence="static_compile",
        expected_justification="Energia e m a (força) não coincidem em ℚ⁷.",
        limitations="Não discute unidades naturais.",
        variants=["Declare F com dimensão [M L T⁻²]."],
        submission=_sub(
            "F com dimensão de energia igual a m a",
            r"F = m a \quad (F\ \text{como energia})",
            {
                "m": {"dimension": M},
                "a": {"dimension": ["0", "1", "-2", "0", "0", "0", "0"]},
                "F": {"dimension": E},
            },
            [],
            [_rel("newton", "F", "==", "m*a")],
        ),
    ),
    _case(
        ident="lib-23-exp-positive",
        theme="fragment_boundaries",
        title="Exponencial positiva",
        question="exp(x)>0 é certificado pelo SMT local?",
        context="Transcendente fora do adapter Z3.",
        recommended_reason="Fronteira do fragmento: verdade clássica, abstenção local.",
        expected_verdict="ABSTAIN",
        expected_evidence="smt_relative",
        expected_justification="exp não é QF_NRA neste encoding.",
        limitations="Não contradiz a análise real; o sistema não cobre o símbolo.",
        variants=["Use x²+1>0, que fecha no SMT."],
        submission=_sub(
            "Exponencial positiva",
            r"e^x > 0",
            {"x": {"dimension": ZERO}},
            [],
            [_rel("exp-pos", "exp(x)", ">", "0")],
        ),
    ),
    _case(
        ident="lib-24-sqrt-identity",
        theme="fragment_boundaries",
        title="Raiz quadrada e potência 1/2",
        question="sqrt(x) = x^(1/2) é certificado?",
        context="Potência fracionária e sqrt exigem domínio futuro.",
        recommended_reason="Limite não suportado, distinto de um erro dimensional.",
        expected_verdict="ABSTAIN",
        expected_evidence="smt_relative",
        expected_justification="Potências fracionárias não entram no adapter SMT.",
        limitations="Há teoria de raízes em x≥0; não está implementada.",
        variants=["Afirme x²≥0."],
        submission=_sub(
            "sqrt versus potência fracionária",
            r"\sqrt{x}=x^{1/2}",
            {"x": {"dimension": ZERO}},
            [{"lhs": "x", "op": ">=", "rhs": "0"}],
            [_rel("root", "sqrt(x)", "==", "x**(1/2)")],
        ),
    ),
    _case(
        ident="lib-25-shift-square",
        theme="identities_and_inequalities",
        title="(x−3)² ≥ 0",
        question="Um quadrado deslocado permanece não negativo?",
        context="Mesma família, constante não trivial.",
        recommended_reason="Evita duplicar só o nome da variável.",
        expected_verdict="ACCEPTED",
        expected_evidence="smt_relative",
        expected_justification="Quadrado de um polinômio.",
        limitations="Não estende a formas de grau ímpar.",
        variants=["(x−3)² ≥ 1 é falso."],
        submission=_sub(
            "Quadrado deslocado",
            r"(x-3)^2 \geq 0",
            {"x": {"dimension": ZERO}},
            [],
            [_rel("shift", "(x-3)**2", ">=", "0")],
        ),
    ),
    _case(
        ident="lib-26-false-shift",
        theme="counterexamples",
        title="(x−3)² ≥ 1 sempre?",
        question="O quadrado deslocado fica sempre acima de 1?",
        context="Par negativo de lib-25.",
        recommended_reason="Caso positivo e negativo da mesma família.",
        expected_verdict="REFUTED",
        expected_evidence="exact_rational_witness",
        expected_justification="x=3 dá 0 ≥ 1 falso.",
        limitations="Testemunha pontual.",
        variants=["Pergunte ≥ 0."],
        submission=_sub(
            "Quadrado deslocado acima de 1",
            r"(x-3)^2 \geq 1",
            {"x": {"dimension": ZERO}},
            [],
            [_rel("shift", "(x-3)**2", ">=", "1")],
        ),
    ),
    _case(
        ident="lib-27-energy-zero-ok",
        theme="dimensional_consistency",
        title="Energia comparada a zero",
        question="Zero literal pode aparecer numa desigualdade energética?",
        context="Zero polimórfico só na fronteira da relação.",
        recommended_reason="Contrasta com a soma ilegítima energia+momento.",
        expected_verdict="ACCEPTED",
        expected_evidence="smt_relative",
        expected_justification="E≥0 com E=m v²/2 e m>0.",
        limitations="Não define origem do potencial.",
        variants=["Some 0*v para não confundir com soma de momento."],
        submission=_sub(
            "Energia comparada a zero",
            r"m v^2 \geq 0,\ m>0",
            {"m": {"dimension": M}, "v": {"dimension": V}},
            [{"lhs": "m", "op": ">", "rhs": "0"}],
            [_rel("energy", "m*v**2", ">=", "0")],
        ),
    ),
    _case(
        ident="lib-28-double-hole",
        theme="proof_gaps",
        title="Identidade e lacuna juntas",
        question="Um passo certo e um buraco geram aceite?",
        context="Agregação conservadora.",
        recommended_reason="Uma obrigação aberta impede ACCEPTED.",
        expected_verdict="ABSTAIN",
        expected_evidence="unavailable",
        expected_justification="x²≥0 fecha, a lacuna não.",
        limitations="Não ranqueia importância da lacuna.",
        variants=["Remova a lacuna."],
        submission=_sub(
            "Identidade com lacuna",
            r"x^2\geq 0\text{ e um passo omitido}",
            {"x": {"dimension": ZERO}},
            [],
            [
                _rel("square", "x**2", ">=", "0"),
                {"kind": "proof_hole", "id": "gap", "description": "Falta o argumento geométrico."},
            ],
        ),
    ),
    _case(
        ident="lib-29-limit-with-assumption",
        theme="supported_and_unsupported_limits",
        title="Limite com premissa extra",
        question="O adapter de limite aceita hipóteses laterais?",
        context="Fora do contrato do CAS local.",
        recommended_reason="Não-suporte documentado, não falha silenciosa.",
        expected_verdict="ABSTAIN",
        expected_evidence="cas_advisory",
        expected_justification="Premissas + infinito não são certificadas juntas.",
        limitations="Pode existir prova analítica à parte.",
        variants=["Remova a premissa."],
        submission=_sub(
            "Limite com premissa",
            r"x>0,\ \lim (2x+1)/(x+1)=2",
            {"x": {"dimension": ZERO}},
            [{"lhs": "x", "op": ">", "rhs": "0"}],
            [
                {
                    "kind": "limit",
                    "id": "ratio",
                    "expression": "(2*x+1)/(x+1)",
                    "variable": "x",
                    "target": "infinity",
                    "expected": "2",
                }
            ],
        ),
    ),
    _case(
        ident="lib-30-interval-box",
        theme="counterexamples",
        title="Afirmação falsa numa caixa racional",
        question="x ≥ 2 pode valer em [-1, 1]?",
        context="Domínio limitado declara caixa para o adapter intervalar e o SMT.",
        recommended_reason="Exercita enclosure exato além do contraexemplo pontual.",
        expected_verdict="REFUTED",
        expected_evidence="interval_enclosure",
        expected_justification="Na caixa [-1,1] o enclosure de x fica abaixo de 2.",
        limitations="A caixa é parte da formalização; não é amostragem gráfica.",
        variants=["Afirme x ≥ -2 na mesma caixa."],
        submission=_sub(
            "x >= 2 na caixa [-1,1]",
            r"x\in[-1,1]\implies x\geq 2",
            {"x": {"dimension": ZERO, "domain_min": "-1", "domain_max": "1"}},
            [],
            [_rel("box", "x", ">=", "2")],
        ),
    ),
    _case(
        ident="lib-31-two-x-equals",
        theme="identities_and_inequalities",
        title="x+x = 2x",
        question="Duplicar é o mesmo que escalar por 2?",
        context="Identidade linear.",
        expected_verdict="ACCEPTED",
        expected_evidence="smt_relative",
        expected_justification="Diferença nula.",
        limitations="Não aborda overflow de ponto flutuante: aqui a aritmética é simbólica.",
        variants=["x+x == 3x é falso."],
        recommended_reason="Caso mínimo de igualdade linear.",
        submission=_sub(
            "Duplicação linear",
            r"x+x=2x",
            {"x": {"dimension": ZERO}},
            [],
            [_rel("double", "x+x", "==", "2*x")],
        ),
    ),
    _case(
        ident="lib-32-false-double",
        theme="counterexamples",
        title="x+x = 3x",
        question="Duplicar é o mesmo que triplicar?",
        context="Par negativo de lib-31.",
        recommended_reason="Família identidade com caso falso.",
        expected_verdict="REFUTED",
        expected_evidence="exact_rational_witness",
        expected_justification="x=1 viola.",
        limitations="Testemunha pontual.",
        variants=["lib-31."],
        submission=_sub(
            "Duplicação versus triplicação",
            r"x+x=3x",
            {"x": {"dimension": ZERO}},
            [],
            [_rel("double", "x+x", "==", "3*x")],
        ),
    ),
    _case(
        ident="lib-33-sum-squares",
        theme="identities_and_inequalities",
        title="Soma de quadrados",
        question="x² + y² ≥ 0?",
        context="Duas variáveis, identidade.",
        recommended_reason="Não é só um rename de x²≥0: há soma.",
        expected_verdict="ACCEPTED",
        expected_evidence="smt_relative",
        expected_justification="Soma de quadrados.",
        limitations="Não prova definitude de formas com termos cruzados arbitrários.",
        variants=["x² + y² ≥ 1 é falso."],
        submission=_sub(
            "Soma de quadrados",
            r"x^2+y^2\geq 0",
            {"x": {"dimension": ZERO}, "y": {"dimension": ZERO}},
            [],
            [_rel("sumsq", "x**2 + y**2", ">=", "0")],
        ),
    ),
    _case(
        ident="lib-34-sum-squares-false",
        theme="counterexamples",
        title="Soma de quadrados ≥ 1",
        question="x² + y² ≥ 1 sempre?",
        context="Par negativo de lib-33.",
        recommended_reason="Origem (0,0) é contraexemplo.",
        expected_verdict="REFUTED",
        expected_evidence="exact_rational_witness",
        expected_justification="x=y=0.",
        limitations="Testemunha pontual.",
        variants=["lib-33."],
        submission=_sub(
            "Soma de quadrados acima de 1",
            r"x^2+y^2\geq 1",
            {"x": {"dimension": ZERO}, "y": {"dimension": ZERO}},
            [],
            [_rel("sumsq", "x**2 + y**2", ">=", "1")],
        ),
    ),
]


THEMES = [
    "dimensional_consistency",
    "identities_and_inequalities",
    "domains_and_singularities",
    "contradictory_premises",
    "counterexamples",
    "supported_and_unsupported_limits",
    "proof_gaps",
    "physics_in_fragment",
    "fragment_boundaries",
]


def by_id(ident):
    for item in CASES:
        if item["id"] == ident:
            return item
    return None


def featured():
    return [item for item in CASES if item.get("featured")]
