"""Didactic library: hand-authored cases with provenance. Not a generalization benchmark."""

from __future__ import annotations

ZERO = ["0"] * 7
M = ["1", "0", "0", "0", "0", "0", "0"]
L = ["0", "1", "0", "0", "0", "0", "0"]
T = ["0", "0", "1", "0", "0", "0", "0"]
V = ["0", "1", "-1", "0", "0", "0", "0"]
E = ["1", "2", "-2", "0", "0", "0", "0"]
P = ["1", "1", "-1", "0", "0", "0", "0"]

SOURCE = {
    "kind": "synthetic",
    "author": "NatalIA maintainers",
    "license": "Same as this repository",
    "note": "Original didactic formalizations, not copied from copyrighted problem sets.",
}


def _rel(claim_id, lhs, op, rhs):
    return {"kind": "relation", "id": claim_id, "lhs": lhs, "op": op, "rhs": rhs}


def _sub(title, latex, variables, assumptions, claims, budget=5000):
    return {
        "schema_version": "1.0",
        "title": title,
        "source_latex": latex,
        "variables": variables,
        "assumptions": assumptions,
        "claims": claims,
        "budget_ms": budget,
    }


def _case(
    *,
    ident,
    theme,
    title,
    question,
    context,
    recommended_reason,
    expected_verdict,
    expected_evidence,
    expected_justification,
    limitations,
    variants,
    submission,
    featured=False,
):
    return {
        "id": ident,
        "theme": theme,
        "title": title,
        "question": question,
        "context": context,
        "recommended_reason": recommended_reason,
        "expected_verdict": expected_verdict,
        "expected_evidence": expected_evidence,
        "expected_justification": expected_justification,
        "source": SOURCE,
        "limitations": limitations,
        "pedagogical_variants": variants,
        "featured": featured,
        "submission": submission,
    }


CASES = [
    _case(
        ident="lib-01-kinetic",
        theme="physics_in_fragment",
        title="Non-negative kinetic energy",
        question="If mass is positive, can classical kinetic energy ever be negative?",
        context="Elementary Newtonian mechanics statement within the polynomial fragment.",
        recommended_reason="First SMT example with real physical dimensions.",
        expected_verdict="ACCEPTED",
        expected_evidence="smt_relative",
        expected_justification="With m > 0, m*v^2 / 2 is a scaled square and cannot be negative.",
        limitations="Does not prove relativity nor define energy outside the declared formula.",
        variants=["Remove m > 0 and observe refutation.", "Add energy to momentum and observe INVALID."],
        submission=_sub(
            "Non-negative kinetic energy",
            r"E_k = \frac{1}{2} m v^2 \geq 0,\quad m>0",
            {"m": {"dimension": M}, "v": {"dimension": V}},
            [{"lhs": "m", "op": ">", "rhs": "0"}],
            [_rel("kinetic-energy", "m*v**2/2", ">=", "0")],
        ),
        featured=True,
    ),
    _case(
        ident="lib-02-square-vs-linear",
        theme="counterexamples",
        title="Square does not dominate identity",
        question="Does x^2 >= x hold for all real numbers?",
        context="False inequality designed to exercise exact rational counterexample generation.",
        recommended_reason="Exposes inspectable counterexample evidence, not just a refutation label.",
        expected_verdict="REFUTED",
        expected_evidence="exact_rational_witness",
        expected_justification="Any x in (0,1) violates the inequality; verified with exact rational arithmetic.",
        limitations="The witness is a single point; visual charts are illustrative.",
        variants=["Restrict to x >= 1 to obtain acceptance in the SMT fragment."],
        submission=_sub(
            "x**2 >= x for reals",
            r"x^2 \geq x \quad \forall x \in \mathbb{R}",
            {"x": {"dimension": ZERO}},
            [],
            [_rel("square-ge-id", "x**2", ">=", "x")],
        ),
        featured=True,
    ),
    _case(
        ident="lib-03-energy-plus-momentum",
        theme="dimensional_consistency",
        title="Energy added to momentum (dimensional mismatch)",
        question="Can energy and linear momentum be summed in the same physical expression?",
        context="Classical dimensional inconsistency caught before solver dispatch.",
        recommended_reason="Demonstrates that the workbench rejects inconsistent formalizations immediately.",
        expected_verdict="INVALID",
        expected_evidence="static_compile",
        expected_justification="SI dimension exponents of energy and momentum differ; summation is invalid.",
        limitations="Does not perform unit scale conversion; dimensional presets define Q^7 powers.",
        variants=["Compare each quantity with zero separately."],
        submission=_sub(
            "Energy added to momentum",
            r"\tfrac12 m v^2 + m v \geq 0",
            {"m": {"dimension": M}, "v": {"dimension": V}},
            [{"lhs": "m", "op": ">", "rhs": "0"}],
            [_rel("mixed", "m*v**2/2 + m*v", ">=", "0")],
        ),
        featured=True,
    ),
    _case(
        ident="lib-04-rational-limit",
        theme="supported_and_unsupported_limits",
        title="Rational limit at infinity",
        question="Is the limit of (2x^2 + 1)/(x^2 + 3) as x approaches infinity equal to 2?",
        context="Advisory CAS evaluation: matching values are indicative, not certified.",
        recommended_reason="Clearly distinguishes indicative computation from formal mathematical certification.",
        expected_verdict="ABSTAIN",
        expected_evidence="cas_advisory",
        expected_justification="SymPy confirms 2, but the formal status remains inconclusive.",
        limitations="Represents a local adapter boundary, not mathematical undecidability.",
        variants=["Use a polynomial identity if an SMT certificate is required."],
        submission=_sub(
            "Rational limit at infinity",
            r"\lim_{x\to\infty}(2x^2+1)/(x^2+3)=2",
            {"x": {"dimension": ZERO}},
            [],
            [
                {
                    "kind": "limit",
                    "id": "ratio",
                    "expression": "(2*x**2+1)/(x**2+3)",
                    "variable": "x",
                    "target": "infinity",
                    "expected": "2",
                }
            ],
        ),
    ),
    _case(
        ident="lib-05-proof-hole",
        theme="proof_gaps",
        title="Incomplete deduction (proof hole)",
        question="Can an explicit proof gap result in an accepted claim?",
        context="The formalizer acknowledges that an intermediate step is missing.",
        recommended_reason="Demonstrates that explicit holes block acceptance unconditionally.",
        expected_verdict="ABSTAIN",
        expected_evidence="unavailable",
        expected_justification="proof_hole obligations remain inconclusive by contract.",
        limitations="The system does not automatically synthesize omitted steps from natural language.",
        variants=["Combine with a false claim: refutation takes precedence."],
        submission=_sub(
            "Incomplete deduction",
            "Geometric step omitted.",
            {"x": {"dimension": ZERO}},
            [],
            [{"kind": "proof_hole", "id": "missing-lemma", "description": "Justification missing."}],
        ),
    ),
    _case(
        ident="lib-06-contradiction",
        theme="contradictory_premises",
        title="Contradictory assumptions",
        question="Do impossible assumptions allow arbitrary conclusions to be proved?",
        context="Guards against vacuous truth and principle of explosion exploitation.",
        recommended_reason="Scientific trust contract: inconsistent premises must not yield acceptance.",
        expected_verdict="ABSTAIN",
        expected_evidence="smt_relative",
        expected_justification="x > 1 and x < 0 is UNSAT; vacuous acceptance is strictly prevented.",
        limitations="Does not classify broader background theories beyond this explicit encoding.",
        variants=["Modify one assumption to restore consistency."],
        submission=_sub(
            "Contradictory assumptions",
            r"x>1 \land x<0 \implies x^2 \geq 0",
            {"x": {"dimension": ZERO}},
            [{"lhs": "x", "op": ">", "rhs": "1"}, {"lhs": "x", "op": "<", "rhs": "0"}],
            [_rel("anyway", "x**2", ">=", "0")],
        ),
    ),
    _case(
        ident="lib-07-singularity",
        theme="domains_and_singularities",
        title="Division x/x == 1 without domain guard",
        question="Is canceling x/x valid for all real numbers?",
        context="Singularity at zero.",
        recommended_reason="Missing domain constraints produce inconclusive results, avoiding silent cancellation.",
        expected_verdict="ABSTAIN",
        expected_evidence="smt_relative",
        expected_justification="Without x != 0, domain safety is unestablished.",
        limitations="Does not perform distribution theory or measure-theoretic regularization.",
        variants=["lib-08 adds explicit x != 0."],
        submission=_sub(
            "x/x == 1 without domain guard",
            r"x/x = 1",
            {"x": {"dimension": ZERO}},
            [],
            [_rel("cancel", "x/x", "==", "1")],
        ),
    ),
    _case(
        ident="lib-08-domain-fixed",
        theme="domains_and_singularities",
        title="Division x/x == 1 with x != 0",
        question="With zero excluded from the domain, does the rational identity hold?",
        context="Same formula with an explicit domain assumption.",
        recommended_reason="Shows that acceptance depends on stated assumptions, not UI heuristics.",
        expected_verdict="ACCEPTED",
        expected_evidence="smt_relative",
        expected_justification="With x != 0, x/x - 1 is identically zero over the domain.",
        limitations="Evaluated over real arithmetic in SMT, not an interactive Lean kernel.",
        variants=["Compare with the unguarded variant in lib-07."],
        submission=_sub(
            "x/x == 1 with x != 0",
            r"x\neq 0 \implies x/x = 1",
            {"x": {"dimension": ZERO}},
            [{"lhs": "x", "op": "!=", "rhs": "0"}],
            [_rel("cancel", "x/x", "==", "1")],
        ),
    ),
    _case(
        ident="lib-09-oscillation",
        theme="supported_and_unsupported_limits",
        title="Oscillatory limit outside fragment",
        question="Is the limit of sin(x)/x as x approaches infinity supported locally?",
        context="Trigonometric functions lie outside the currently implemented asymptotic fragment.",
        recommended_reason="Transparently documents non-supported features.",
        expected_verdict="ABSTAIN",
        expected_evidence="cas_advisory",
        expected_justification="sin(x) is not supported; result is inconclusive in this adapter.",
        limitations="Standard calculus applies, but this local adapter does not evaluate it.",
        variants=["Replace with a rational polynomial ratio."],
        submission=_sub(
            "Oscillatory limit",
            r"\lim_{x\to\infty}\sin(x)/x",
            {"x": {"dimension": ZERO}},
            [],
            [
                {
                    "kind": "limit",
                    "id": "osc",
                    "expression": "sin(x)/x",
                    "variable": "x",
                    "target": "infinity",
                    "expected": "0",
                }
            ],
        ),
    ),
    _case(
        ident="lib-10-square-nonneg",
        theme="identities_and_inequalities",
        title="Non-negative square",
        question="Does x^2 >= 0 hold for all real numbers?",
        context="Minimal real SMT identity.",
        recommended_reason="Concise positive benchmark for guided mode exploration.",
        expected_verdict="ACCEPTED",
        expected_evidence="smt_relative",
        expected_justification="Negation requires x^2 < 0, which is UNSAT in QF_NRA.",
        limitations="Does not automatically generalize to arbitrary multivariate forms without SOS.",
        variants=["Change to x^2 >= 1 to observe refutation."],
        submission=_sub(
            "Non-negative square",
            r"x^2 \geq 0",
            {"x": {"dimension": ZERO}},
            [],
            [_rel("square", "x**2", ">=", "0")],
        ),
    ),
    _case(
        ident="lib-11-binomial",
        theme="identities_and_inequalities",
        title="Binomial expansion identity",
        question="Does (x + 1)^2 equal x^2 + 2x + 1?",
        context="Univariate polynomial expansion.",
        recommended_reason="Acceptance via algebraic identity without physical dimensions.",
        expected_verdict="ACCEPTED",
        expected_evidence="smt_relative",
        expected_justification="Difference polynomial is identically zero.",
        limitations="Does not formalize general binomial theorem for arbitrary powers.",
        variants=["Change coefficient 2 to 3 to observe refutation."],
        submission=_sub(
            "Binomial identity",
            r"(x+1)^2 = x^2+2x+1",
            {"x": {"dimension": ZERO}},
            [],
            [_rel("expand", "(x+1)**2", "==", "x**2 + 2*x + 1")],
        ),
    ),
    _case(
        ident="lib-12-restricted-true",
        theme="identities_and_inequalities",
        title="x^2 >= x under assumption x >= 1",
        question="Does the false inequality become valid under a restricted domain?",
        context="Pedagogical refinement of lib-02.",
        recommended_reason="Illustrates how adding domain assumptions changes the formal outcome.",
        expected_verdict="ACCEPTED",
        expected_evidence="smt_relative",
        expected_justification="On [1, infinity), the parabola strictly dominates the identity line.",
        limitations="Extra assumptions are not automatic fixes for the original general claim.",
        variants=["Test x >= 0: remains refuted."],
        submission=_sub(
            "x**2 >= x for x >= 1",
            r"x\geq 1 \implies x^2 \geq x",
            {"x": {"dimension": ZERO}},
            [{"lhs": "x", "op": ">=", "rhs": "1"}],
            [_rel("square-ge-id", "x**2", ">=", "x")],
        ),
    ),
    _case(
        ident="lib-13-restricted-false",
        theme="counterexamples",
        title="x^2 >= x under assumption x >= 0",
        question="Is non-negativity sufficient for x^2 >= x?",
        context="The restricted domain still contains the open interval (0, 1).",
        recommended_reason="Shows that insufficient domain restrictions fail to rescue false claims.",
        expected_verdict="REFUTED",
        expected_evidence="exact_rational_witness",
        expected_justification="x = 1/2 >= 0 and (1/2)^2 = 1/4 < 1/2.",
        limitations="Witness coordinates depend on stated premises.",
        variants=["Raise threshold to x >= 1."],
        submission=_sub(
            "x**2 >= x for x >= 0",
            r"x\geq 0 \implies x^2 \geq x",
            {"x": {"dimension": ZERO}},
            [{"lhs": "x", "op": ">=", "rhs": "0"}],
            [_rel("square-ge-id", "x**2", ">=", "x")],
        ),
    ),
    _case(
        ident="lib-14-mass-plus-time",
        theme="dimensional_consistency",
        title="Mass added to time (dimensional mismatch)",
        question="Does m + t represent a valid physical quantity?",
        context="Elementary SI dimensional incompatibility.",
        recommended_reason="Dimensional validation error without energy terms.",
        expected_verdict="INVALID",
        expected_evidence="static_compile",
        expected_justification="Mass and time cannot be added together.",
        limitations="Does not parse natural unit systems where c = G = 1.",
        variants=["Use m*t if an action or phase space volume is intended."],
        submission=_sub(
            "Mass added to time",
            r"m+t \geq 0",
            {"m": {"dimension": M}, "t": {"dimension": T}},
            [],
            [_rel("mix", "m+t", ">=", "0")],
        ),
    ),
    _case(
        ident="lib-15-length-plus-velocity",
        theme="dimensional_consistency",
        title="Length added to velocity",
        question="Is length + velocity a valid physical expression?",
        context="Incompatible SI exponent pairs.",
        recommended_reason="Demonstrates comprehensive SI dimensional checks beyond mass.",
        expected_verdict="INVALID",
        expected_evidence="static_compile",
        expected_justification="[L] != [L T^-1].",
        limitations="Dimensional presets do not convert units (e.g. km/h to m/s).",
        variants=["Compare length and velocity to zero in separate claims."],
        submission=_sub(
            "Length added to velocity",
            r"\ell + v \geq 0",
            {"ell": {"dimension": L}, "v": {"dimension": V}},
            [],
            [_rel("mix", "ell + v", ">=", "0")],
        ),
    ),
    _case(
        ident="lib-16-x-positive-false",
        theme="counterexamples",
        title="Are all real numbers positive?",
        question="Does x > 0 hold unconditionally for all real numbers?",
        context="Immediate refutation case.",
        recommended_reason="Simple counterexample for examining variable substitutions.",
        expected_verdict="REFUTED",
        expected_evidence="exact_rational_witness",
        expected_justification="x = 0 and negative x values violate x > 0.",
        limitations="Does not analyze non-standard ordered algebraic fields.",
        variants=["Add assumption x > 1."],
        submission=_sub(
            "All reals are positive",
            r"x>0",
            {"x": {"dimension": ZERO}},
            [],
            [_rel("pos", "x", ">", "0")],
        ),
    ),
    _case(
        ident="lib-17-square-lt-zero",
        theme="contradictory_premises",
        title="Strictly negative square assumption",
        question="Does any real number satisfy x^2 < 0?",
        context="Impossible assumption used as a premise.",
        recommended_reason="Vacuous truth prevention without paired linear inequalities.",
        expected_verdict="ABSTAIN",
        expected_evidence="smt_relative",
        expected_justification="x^2 < 0 is UNSAT; vacuous acceptance is blocked.",
        limitations="Real closed field axioms are restricted to standard arithmetic.",
        variants=["Use x^2 <= -1."],
        submission=_sub(
            "Premise x**2 < 0",
            r"x^2<0 \implies x=0",
            {"x": {"dimension": ZERO}},
            [{"lhs": "x**2", "op": "<", "rhs": "0"}],
            [_rel("then-zero", "x", "==", "0")],
        ),
    ),
    _case(
        ident="lib-18-reciprocal-product",
        theme="domains_and_singularities",
        title="x * (1/x) == 1 with domain assumption",
        question="Does multiplication by the reciprocal yield 1 when zero is excluded?",
        context="Alternative form of lib-08.",
        recommended_reason="Tests reciprocal multiplication with explicit non-zero domain guards.",
        expected_verdict="ACCEPTED",
        expected_evidence="smt_relative",
        expected_justification="With x != 0, the product is identically 1.",
        limitations="Does not evaluate one-sided limits at zero.",
        variants=["Remove the assumption x != 0."],
        submission=_sub(
            "Product with reciprocal",
            r"x\neq 0 \implies x\cdot(1/x)=1",
            {"x": {"dimension": ZERO}},
            [{"lhs": "x", "op": "!=", "rhs": "0"}],
            [_rel("inv", "x*(1/x)", "==", "1")],
        ),
    ),
    _case(
        ident="lib-19-reciprocal-open",
        theme="domains_and_singularities",
        title="x * (1/x) == 1 without domain guard",
        question="Does x * (1/x) == 1 hold without excluding zero?",
        context="Negative companion case to lib-18.",
        recommended_reason="Highlights supported vs unsupported domain boundaries within the same theme.",
        expected_verdict="ABSTAIN",
        expected_evidence="smt_relative",
        expected_justification="Potential division by zero without domain guard.",
        limitations="Operational fragment boundary, not mathematical impossibility.",
        variants=["See lib-18."],
        submission=_sub(
            "Product with reciprocal without domain guard",
            r"x\cdot(1/x)=1",
            {"x": {"dimension": ZERO}},
            [],
            [_rel("inv", "x*(1/x)", "==", "1")],
        ),
    ),
    _case(
        ident="lib-20-kinetic-unrestricted",
        theme="physics_in_fragment",
        title="Kinetic energy without positive mass",
        question="Does classical kinetic energy remain non-negative if mass is unrestricted?",
        context="Mass can take negative values in unconstrained real encodings.",
        recommended_reason="Physically refutable case within solver capabilities.",
        expected_verdict="REFUTED",
        expected_evidence="exact_rational_witness",
        expected_justification="Negative mass with v != 0 produces negative kinetic energy.",
        limitations="Does not assert negative mass exists physically in nature.",
        variants=["Restore assumption m > 0."],
        submission=_sub(
            "Kinetic energy without m > 0",
            r"\tfrac12 m v^2 \geq 0",
            {"m": {"dimension": M}, "v": {"dimension": V}},
            [],
            [_rel("kinetic-energy", "m*v**2/2", ">=", "0")],
        ),
    ),
    _case(
        ident="lib-21-momentum-nonneg",
        theme="physics_in_fragment",
        title="Is momentum always non-negative?",
        question="Does m*v >= 0 hold whenever m > 0?",
        context="Velocity is a directional scalar in 1D mechanics and can be negative.",
        recommended_reason="False physical statement within the supported fragment.",
        expected_verdict="REFUTED",
        expected_evidence="exact_rational_witness",
        expected_justification="Negative velocity refutes the claim when mass is positive.",
        limitations="Does not model 3D vector spaces.",
        variants=["Use m*v^2 >= 0 instead."],
        submission=_sub(
            "Momentum always non-negative",
            r"m>0 \implies m v \geq 0",
            {"m": {"dimension": M}, "v": {"dimension": V}},
            [{"lhs": "m", "op": ">", "rhs": "0"}],
            [_rel("momentum", "m*v", ">=", "0")],
        ),
    ),
    _case(
        ident="lib-22-force-balance",
        theme="physics_in_fragment",
        title="Force declared as energy in Newton's second law",
        question="If F is declared with energy dimensions, does F = m*a compile?",
        context="Dimensional mismatch in Newton's second law.",
        recommended_reason="Invalid physical model: declared dimension conflicts with equation.",
        expected_verdict="INVALID",
        expected_evidence="static_compile",
        expected_justification="Energy [M L^2 T^-2] and force [M L T^-2] do not match.",
        limitations="Does not support natural unit systems.",
        variants=["Declare F with dimension [M L T^-2]."],
        submission=_sub(
            "Force with energy dimension equals m*a",
            r"F = m a \quad (F\ \text{as energy})",
            {
                "m": {"dimension": M},
                "a": {"dimension": ["0", "1", "-2", "0", "0", "0", "0"]},
                "F": {"dimension": E},
            },
            [],
            [_rel("newton", "F", "==", "m*a")],
        ),
    ),
    _case(
        ident="lib-23-exp-positive",
        theme="fragment_boundaries",
        title="Positive exponential function",
        question="Can exp(x) > 0 be certified by the local SMT solver?",
        context="Transcendental functions lie outside the quantifier-free polynomial fragment.",
        recommended_reason="Clear fragment boundary: mathematical truth versus local solver coverage.",
        expected_verdict="ABSTAIN",
        expected_evidence="smt_relative",
        expected_justification="exp is not supported in the local QF_NRA encoding.",
        limitations="Does not contradict real analysis; workbench explicitly marks unhandled symbols.",
        variants=["Use x^2 + 1 > 0, which discharges in SMT."],
        submission=_sub(
            "Positive exponential",
            r"e^x > 0",
            {"x": {"dimension": ZERO}},
            [],
            [_rel("exp-pos", "exp(x)", ">", "0")],
        ),
    ),
    _case(
        ident="lib-24-sqrt-identity",
        theme="fragment_boundaries",
        title="Square root and fractional power 1/2",
        question="Is sqrt(x) == x^(1/2) certified?",
        context="Fractional powers and radicals require future domain extensions.",
        recommended_reason="Demonstrates an unsupported function distinct from dimensional errors.",
        expected_verdict="ABSTAIN",
        expected_evidence="smt_relative",
        expected_justification="Fractional powers are not handled in the SMT adapter.",
        limitations="Root theory on non-negative reals is well established but outside this fragment.",
        variants=["Assert x^2 >= 0 instead."],
        submission=_sub(
            "sqrt versus fractional power",
            r"\sqrt{x}=x^{1/2}",
            {"x": {"dimension": ZERO}},
            [{"lhs": "x", "op": ">=", "rhs": "0"}],
            [_rel("root", "sqrt(x)", "==", "x**(1/2)")],
        ),
    ),
    _case(
        ident="lib-25-shift-square",
        theme="identities_and_inequalities",
        title="Shifted square (x - 3)^2 >= 0",
        question="Does a shifted square remain non-negative for all real numbers?",
        context="Polynomial square with a non-zero shift constant.",
        recommended_reason="Verifies polynomial sum-of-squares with non-trivial constants.",
        expected_verdict="ACCEPTED",
        expected_evidence="smt_relative",
        expected_justification="Square of a real polynomial.",
        limitations="Does not generalize to odd-degree polynomials.",
        variants=["(x - 3)^2 >= 1 is refuted."],
        submission=_sub(
            "Shifted square",
            r"(x-3)^2 \geq 0",
            {"x": {"dimension": ZERO}},
            [],
            [_rel("shift", "(x-3)**2", ">=", "0")],
        ),
    ),
    _case(
        ident="lib-26-false-shift",
        theme="counterexamples",
        title="Shifted square (x - 3)^2 >= 1",
        question="Does (x - 3)^2 >= 1 hold for all real numbers?",
        context="Refuted counterpart to lib-25.",
        recommended_reason="Provides positive and negative pairs within the same family.",
        expected_verdict="REFUTED",
        expected_evidence="exact_rational_witness",
        expected_justification="At x = 3, 0 >= 1 is false.",
        limitations="Single point witness.",
        variants=["Ask for >= 0 instead."],
        submission=_sub(
            "Shifted square above 1",
            r"(x-3)^2 \geq 1",
            {"x": {"dimension": ZERO}},
            [],
            [_rel("shift", "(x-3)**2", ">=", "1")],
        ),
    ),
    _case(
        ident="lib-27-energy-zero-ok",
        theme="dimensional_consistency",
        title="Energy compared to zero",
        question="Can a literal zero appear in an energy inequality?",
        context="Polymorphic zero is valid at the boundary of a relational comparison.",
        recommended_reason="Contrasts valid zero boundary comparison with invalid dimensional addition.",
        expected_verdict="ACCEPTED",
        expected_evidence="smt_relative",
        expected_justification="E >= 0 with E = m*v^2 and m > 0.",
        limitations="Does not specify gauge or potential energy zero-point.",
        variants=["Add 0*v to test dimensional addition preservation."],
        submission=_sub(
            "Energy compared to zero",
            r"m v^2 \geq 0,\ m>0",
            {"m": {"dimension": M}, "v": {"dimension": V}},
            [{"lhs": "m", "op": ">", "rhs": "0"}],
            [_rel("energy", "m*v**2", ">=", "0")],
        ),
    ),
    _case(
        ident="lib-28-double-hole",
        theme="proof_gaps",
        title="Identity combined with proof gap",
        question="Does a valid identity paired with an open proof gap yield acceptance?",
        context="Conservative multi-obligation aggregation.",
        recommended_reason="Demonstrates that any open obligation prevents ACCEPTED.",
        expected_verdict="ABSTAIN",
        expected_evidence="unavailable",
        expected_justification="x^2 >= 0 is verified, but the proof gap remains open.",
        limitations="Does not rank relative significance of proof gaps.",
        variants=["Remove the proof gap obligation."],
        submission=_sub(
            "Identity with proof gap",
            r"x^2\geq 0\text{ with an omitted step}",
            {"x": {"dimension": ZERO}},
            [],
            [
                _rel("square", "x**2", ">=", "0"),
                {"kind": "proof_hole", "id": "gap", "description": "Geometric argument omitted."},
            ],
        ),
    ),
    _case(
        ident="lib-29-limit-with-assumption",
        theme="supported_and_unsupported_limits",
        title="Limit with lateral assumption",
        question="Does the limit adapter support external assumption constraints?",
        context="Outside the contract of the local CAS limit adapter.",
        recommended_reason="Documented unsupported feature, avoiding silent incorrect evaluation.",
        expected_verdict="ABSTAIN",
        expected_evidence="cas_advisory",
        expected_justification="Hypotheses combined with infinite limits are not certified together.",
        limitations="Independent analytical proof may exist.",
        variants=["Remove the assumption."],
        submission=_sub(
            "Limit with assumption",
            r"x>0,\ \lim (2x+1)/(x+1)=2",
            {"x": {"dimension": ZERO}},
            [{"lhs": "x", "op": ">", "rhs": "0"}],
            [
                {
                    "kind": "limit",
                    "id": "ratio",
                    "expression": "(2*x+1)/(x+1)",
                    "variable": "x",
                    "target": "infinity",
                    "expected": "2",
                }
            ],
        ),
    ),
    _case(
        ident="lib-30-interval-box",
        theme="counterexamples",
        title="False claim within rational box enclosure",
        question="Can x >= 2 hold on the interval [-1, 1]?",
        context="Bounded domain declaring an exact box for interval arithmetic and SMT.",
        recommended_reason="Exercises exact interval enclosure alongside point counterexample search.",
        expected_verdict="REFUTED",
        expected_evidence="interval_enclosure",
        expected_justification="On the box [-1, 1], the upper bound of x is 1 < 2.",
        limitations="The box is part of the formalization, not a heuristic graphical sample.",
        variants=["Assert x >= -2 on the same interval."],
        submission=_sub(
            "x >= 2 in box [-1,1]",
            r"x\in[-1,1]\implies x\geq 2",
            {"x": {"dimension": ZERO, "domain_min": "-1", "domain_max": "1"}},
            [],
            [_rel("box", "x", ">=", "2")],
        ),
    ),
    _case(
        ident="lib-31-two-x-equals",
        theme="identities_and_inequalities",
        title="Linear identity x + x == 2x",
        question="Is doubling a variable identical to scaling by 2?",
        context="Linear polynomial identity.",
        expected_verdict="ACCEPTED",
        expected_evidence="smt_relative",
        expected_justification="Difference polynomial is identically zero.",
        limitations="Does not address floating-point overflow; arithmetic is exact symbolic.",
        variants=["x + x == 3x is refuted."],
        recommended_reason="Minimal linear identity case.",
        submission=_sub(
            "Linear duplication",
            r"x+x=2x",
            {"x": {"dimension": ZERO}},
            [],
            [_rel("double", "x+x", "==", "2*x")],
        ),
    ),
    _case(
        ident="lib-32-false-double",
        theme="counterexamples",
        title="Linear equality x + x == 3x",
        question="Is doubling a variable identical to scaling by 3?",
        context="Refuted counterpart to lib-31.",
        recommended_reason="Linear identity paired with a falsifying example.",
        expected_verdict="REFUTED",
        expected_evidence="exact_rational_witness",
        expected_justification="Violated at x = 1.",
        limitations="Single point witness.",
        variants=["See lib-31."],
        submission=_sub(
            "Duplication versus triplication",
            r"x+x=3x",
            {"x": {"dimension": ZERO}},
            [],
            [_rel("double", "x+x", "==", "3*x")],
        ),
    ),
    _case(
        ident="lib-33-sum-squares",
        theme="identities_and_inequalities",
        title="Sum of squares x^2 + y^2 >= 0",
        question="Does x^2 + y^2 >= 0 hold for all real numbers x and y?",
        context="Bivariate polynomial sum of squares.",
        recommended_reason="Validates multivariate sum-of-squares beyond univariate expressions.",
        expected_verdict="ACCEPTED",
        expected_evidence="smt_relative",
        expected_justification="Sum of two real squares cannot be negative.",
        limitations="Does not compute SOS decompositions for arbitrary non-diagonal forms.",
        variants=["x^2 + y^2 >= 1 is refuted."],
        submission=_sub(
            "Sum of squares",
            r"x^2+y^2\geq 0",
            {"x": {"dimension": ZERO}, "y": {"dimension": ZERO}},
            [],
            [_rel("sumsq", "x**2 + y**2", ">=", "0")],
        ),
    ),
    _case(
        ident="lib-34-sum-squares-false",
        theme="counterexamples",
        title="Sum of squares x^2 + y^2 >= 1",
        question="Does x^2 + y^2 >= 1 hold for all real numbers?",
        context="Refuted counterpart to lib-33.",
        recommended_reason="Origin (0, 0) provides an immediate exact counterexample.",
        expected_verdict="REFUTED",
        expected_evidence="exact_rational_witness",
        expected_justification="Violated at x = 0, y = 0.",
        limitations="Single point witness.",
        variants=["See lib-33."],
        submission=_sub(
            "Sum of squares above 1",
            r"x^2+y^2\geq 1",
            {"x": {"dimension": ZERO}, "y": {"dimension": ZERO}},
            [],
            [_rel("sumsq", "x**2 + y**2", ">=", "1")],
        ),
    ),
]


THEMES = [
    "dimensional_consistency",
    "identities_and_inequalities",
    "domains_and_singularities",
    "contradictory_premises",
    "counterexamples",
    "supported_and_unsupported_limits",
    "proof_gaps",
    "physics_in_fragment",
    "fragment_boundaries",
]


def by_id(ident):
    for item in CASES:
        if item["id"] == ident:
            return item
    return None


def featured():
    return [item for item in CASES if item.get("featured")]
